Repository UMC-partNerd/front, pull requests merged in 2025-02, with the labels that each got.

#76 버튼 중복 오류, 모집 등록 오류 해결
  src/App.jsx
  src/components/partnerd-search.jsx
Labels: feature

#78 부리더 권한 API 연결
  src/components/contact/permission-registration.jsx
  src/hooks/useTeamMembers.js
  src/pages/TeamRegistration.jsx
  src/styled-components/contact/styled-permission-registration.jsx
Labels: feature

#81 페이지 상단 배너
  src/components/partnerd-search.jsx
  src/components/project-collaboration.jsx
  src/components/project-promotion.jsx
  src/components/project-recruitment.jsx
Labels: feature

#86 팀페이지 권한 위임하기
  src/components/contact/leader-change.jsx
  src/hooks/useLeaderChange.js
  src/pages/TeamMangement.jsx
Labels: feature

#95 Feat/93
  src/components/collaboration-detail/comments/Comment.jsx
  src/components/home/Club.jsx
  src/components/home/Collaboration.jsx
  src/components/home/Project.jsx
  src/components/project-collaboration.jsx
  src/components/project-promotion.jsx
  src/hooks/useProjectCollaboration.js
  src/hooks/useProjectPromotion.js
  src/pages/Communitypage.jsx
  src/pages/collaboration-pages/CollaborationDetailPage.jsx
  src/styled-components/styled-Card.jsx
  src/styled-components/styled-Club.jsx
  src/styled-components/styled-Project.jsx
Labels: enhancement, feature

#99 홍보 페이지 무한 로딩 수정
  src/components/project-promotion.jsx
  src/hooks/useProjectPromotion.js
Labels: bug

#104 커뮤니티 top10 api 연결
  src/components/community/Top10-rank.jsx
  src/components/partnerd-search.jsx
  src/components/project-collaboration.jsx
  src/hooks/usePartnerSearch.js
  src/hooks/useProjectCollaboration.js
  src/hooks/useTopRank.js
  src/styled-components/styled-Top10-rank.jsx
  src/styled-components/styled-partnerd-search.jsx
Labels: feature

#112 [REFACTOR] websocket 연결 경로 수정 및 JWT 토큰 전달
  src/components/chat/chat.jsx
Labels: refactor

#113 [FIX] websocket 연결 경로 수정 및 JWT 토큰 전달 -> 배포 URL 로변경
  src/components/chat/chat.jsx
Labels: refactor

#114 [REFACTOR] 채팅방 변경 시 subscribe 만 변경 웹소켓은 유지, 로그인 시 닉네임 localStorage 추가
  src/components/chat/chat.jsx
  src/components/login/KakaoCallback.jsx
Labels: refactor

#115 [REFACTOR] No offset 페이징에 맞게 api 요청 수정
  src/hooks/useProjectCollaboration.js
Labels: refactor

#116 [FIX] 오타 수정
  src/components/login/KakaoCallback.jsx
Labels: wontfix
